### ISSUE TITLE
[1.14.4] Problem loading version.

### ISSUE THREAD

**Issue by ProsperCraft** [ianm1647/MoreProgression#1]
moreprog-1.14.4-0.2.8.1

![99aceb4dca395c0df68b5fa1281fdff9](https://user-images.githubusercontent.com/4427684/61764489-af582580-ad96-11e9-8c8d-8f9945f0d5cb.png)

**Comment by kwpugh** [comment]
Same here.  Pile on!       ;)

**Comment by ianm1647** [comment]
it's fixed

**Comment by ianm1647** [comment]
it was fixed immediately the other day
